### ISSUE TITLE
float slider behaves as int when given 1.0

### ISSUE THREAD

**Issue by trackme518** [KrabCode/LazyGui#279]
When declaring slider as  `float currVolume = gui.slider("volume", 1.0, 0.0, 1.0);` it will create a GUI slider that can only be 0 or 1 - it behaves as int. However when I declare it as `float currVolume = gui.slider("volume", 0.987, 0.0, 1.0);` it behaves as float. Slider should always behave as float unless specifically declared as intSlider()

**Comment by KrabCode** [comment]
it may appear like an int slider because of the default precision, could you please try if using the scroll wheel over that slider changes anything? it should allow you to have float precision

**Comment by KrabCode** [comment]
it still might be worth it to investigate this default, [0, 1] is a common range to have and a float slider should not appear like you can only set 0 or 1 on it by default, perhaps it can be 0.1 default precision in this case, so you'd be able to set things like 0.7... maybe even 0.01 precision would make sense here

**Comment by trackme518** [comment]
I would recommend setting it to full float precision always but displaying only 0.01 precision visually. If somebody wants int, they can declare it with sliderInt or by int() the output of float slider. You can also decide the visual output minimum step by looking at declared min and max - when it is lower than 1 maybe show 3-5 decimal places, when the difference between min and max is higher set to 2 decimal places, when higher than 100 leave it 1 decimal place or even display as int. When user does not declare min and max just show one decimal place by default?

**Comment by KrabCode** [comment]
What is displayed visually is already decoupled from the actual value used and returned by the slider - the float slider that displays 0 or 1 can already represent 0.4532, aka full float precision (it's not really full float precision, float can represent way finer precision than 0.0001, but you run into some problems with internal floating point logic and I never want to display scientific notation, so there's a limit to what the gui supports), you just have to either in your code set its default value to something with more digits after the floating point which sets the default precision accordingly to fit that value, or at runtime, move the scroll wheel over it to change how precisely it displays and how slowly a mouse drag changes the value. <- it seems like you don't mention this scrolling option yet, it might be useful, please try it.

I think I'm just going to adjust the default displayed precision in this case.

You can take a look at the [SliderNode](https://github.com/KrabCode/LazyGui/blob/master/src/main/java/com/krab/lazy/nodes/SliderNode.java) class, it contains a precisionRange array that describes the allowed display range and has the setSensiblePrecision() method which tries to infer the most useful precision to start with, and is the only part that needs to be adjusted here in my opinion. To work like, as you say, when the distance between min/max is <= 1 then it should show something like 0.01 precision and not 1. I don't think setting a full 0.0001 precision is always useful, you usually want your mouse drag across the screen to actually move the slider meaningfully through the whole range (like from 0 to 0.25), not just to 0.0025.

The [int slider](https://github.com/KrabCode/LazyGui/blob/master/src/main/java/com/krab/lazy/nodes/SliderIntNode.java) is a special case of a SliderNode where its value is returned and displayed in a floored state and the display / mouse drag precision has a lower bound where it won't go under 0.1 but otherwise it acts the same as a float slider.

**Comment by trackme518** [comment]
Hi, thanks a lot! I just tested it and it works.
