### ISSUE TITLE
Suggestion: some way to provide an optional curve to a slider

### ISSUE THREAD

**Issue by alexhunsley** [KrabCode/LazyGui#282]
Often I want a slider that is non-linear: for example, if it controls the rotation of an object, I'm interested in fine adjustments to small values especially, but want higher values still to be accessible (and without having to adjust the precision of mouse the usual way).

Currently I'm doing a float -> float function myself to achieve this.

Could the slider (and similar) in lazyGui take an optional float -> float function at init, and apply it to the value of slider before reporting back to the processing sketch?

**Comment by KrabCode** [comment]
I don't see how this would be useful, wouldn't it be the same thing as saying `slider("rotation") * 0.01` which you can do already? Could you provide some pseudo-code of a reasonable use case for these functions?

Functions for when buttons are pressed on the other hand would make a lot of sense to me.

**Comment by alexhunsley** [comment]
Quite right, this can certainly be done in the user's own sketch code. It's more for ergonomics, I guess, the idea of doing it at setup time then forgetting about it in main loop.

**Comment by KrabCode** [comment]
I'm open to adding functions as parameters, but there's a few problems with it - one is that it's not trivial in java, you probably have to kind of provide a whole template of a tiny class that implements some interface... and that's not very beginner friendly, but that's probably a minor issue since the function parameter can be optional or hidden in a slightly differently named LazyGui API call, like sliderFunction("mySlider", <some way to pass a function> ).

The main issue in my opinion with what you describe is that it clashes ideologically with the main "ergonomics" idea of LazyGui - that is to initialize nothing in setup() besides the main LazyGui instance, only mention your control elements in draw() at the place where their values are actually needed. The idea is to concentrate everything related to one slider near that one location, so it's easier to edit and you don't have to jump all the way to the top to adjust something.

This was born out of a frustration with existing tools that did require extensive setup() code for stuff like functions, window sizes, positioning, tree structure of the elements... before being able to use them in draw().

**Comment by alexhunsley** [comment]
Thanks for the context/background!
