### ISSUE TITLE
Suggestion: loop and bounce auto modes on sliders

### ISSUE THREAD

**Issue by alexhunsley** [KrabCode/LazyGui#283]
It can be nice to have your sketch animating parameters automatically for demo etc.

How about a keyboard shortcut (s) to make the slider under mouse do "loop forwards", "loop backwards", and "bounce" (forward then back) over its values continuously? And a speed up/down would be useful too.

If combined with the slider optional mapping function suggestion, this could be really sweet for demos: eg combine a sine function with "bounce" mode.

Also, the slider optional mapping function idea (see other suggestion) would give a really natural place to prove these automatic adjusting sliders. Just stick the slider adjustment function "ahead" of any user provided mapping (compose them).
Like: slider_value = user_func(auto_slider_func(slider _position)).

I completely understand if these are outside the remit of LazyGui, though :)

Again, happy to look into it.

**Comment by KrabCode** [comment]
Well there's already the `sliderSet("rotation", newValue)` function which can use the previous slider value or ignore it completely, you can control what happens to the slider value pretty precisely - the problem is that the slider now becomes a display slider and cannot be controlled manually, since it's set from code every frame.

**Comment by KrabCode** [comment]
To see what I mean - take a look at the GeneralExample in the pde examples, maybe the code under `// change GUI values from code` can be adapted to do what you want.
